delete from comment;
delete from contact;
delete from event;
delete from gallery;
delete from gallery_images;
delete from image;
delete from index_part;
delete from item where id>2;
delete from message;
delete from news;
delete from page;
delete from region;
delete from region_part;
delete from toplist;
delete from toplist_element;
delete from toplist_element_relation;
delete from user where id>1;
delete from user_part;
delete from user_part_config;
delete from user_registration;